/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MainExampleIndexImport } from './routes/main-example/index'
import { Route as MainExampleIdImport } from './routes/main-example/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainExampleIndexRoute = MainExampleIndexImport.update({
  id: '/main-example/',
  path: '/main-example/',
  getParentRoute: () => rootRoute,
} as any)

const MainExampleIdRoute = MainExampleIdImport.update({
  id: '/main-example/$id',
  path: '/main-example/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/main-example/$id': {
      id: '/main-example/$id'
      path: '/main-example/$id'
      fullPath: '/main-example/$id'
      preLoaderRoute: typeof MainExampleIdImport
      parentRoute: typeof rootRoute
    }
    '/main-example/': {
      id: '/main-example/'
      path: '/main-example'
      fullPath: '/main-example'
      preLoaderRoute: typeof MainExampleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-example/$id': typeof MainExampleIdRoute
  '/main-example': typeof MainExampleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-example/$id': typeof MainExampleIdRoute
  '/main-example': typeof MainExampleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/main-example/$id': typeof MainExampleIdRoute
  '/main-example/': typeof MainExampleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main-example/$id' | '/main-example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main-example/$id' | '/main-example'
  id: '__root__' | '/' | '/main-example/$id' | '/main-example/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainExampleIdRoute: typeof MainExampleIdRoute
  MainExampleIndexRoute: typeof MainExampleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainExampleIdRoute: MainExampleIdRoute,
  MainExampleIndexRoute: MainExampleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main-example/$id",
        "/main-example/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/main-example/$id": {
      "filePath": "main-example/$id.tsx"
    },
    "/main-example/": {
      "filePath": "main-example/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
