/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MainIndexImport } from './routes/main/index'
import { Route as MainIdImport } from './routes/main/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => rootRoute,
} as any)

const MainIdRoute = MainIdImport.update({
  id: '/main/$id',
  path: '/main/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/main/$id': {
      id: '/main/$id'
      path: '/main/$id'
      fullPath: '/main/$id'
      preLoaderRoute: typeof MainIdImport
      parentRoute: typeof rootRoute
    }
    '/main/': {
      id: '/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main/$id': typeof MainIdRoute
  '/main': typeof MainIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main/$id': typeof MainIdRoute
  '/main': typeof MainIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/main/$id': typeof MainIdRoute
  '/main/': typeof MainIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main/$id' | '/main'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main/$id' | '/main'
  id: '__root__' | '/' | '/main/$id' | '/main/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainIdRoute: typeof MainIdRoute
  MainIndexRoute: typeof MainIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainIdRoute: MainIdRoute,
  MainIndexRoute: MainIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main/$id",
        "/main/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/main/$id": {
      "filePath": "main/$id.tsx"
    },
    "/main/": {
      "filePath": "main/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
