import { QueryBuilder } from '../src/builder/QueryBuilder';

describe('QueryBuilder stress test', () => {
  type TData = { readonly sym: unique symbol };
  type TVar = { params: { id: number } };
  type TErr = { readonly sym: unique symbol };

  const qb = new QueryBuilder({ queryFn: () => 0 })
    .withData<TData>()
    .withVars<TVar>()
    .withError<TErr>()
    .withClient(null!)
    .withPagination({ getNextPageParam: null! });

  it('should handle at least 100 preprocessors', () => {
    const nqb = qb
      .withPreprocessor<{ id1: number }>((vars) => ({ ...vars, params: { id: vars.id1 } }))
      .withPreprocessor<{ id2: number }>((vars) => ({ id1: vars.id2 }))
      .withPreprocessor<{ id3: number }>((vars) => ({ id2: vars.id3 }))
      .withPreprocessor<{ id4: number }>((vars) => ({ id3: vars.id4 }))
      .withPreprocessor<{ id5: number }>((vars) => ({ id4: vars.id5 }))
      .withPreprocessor<{ id6: number }>((vars) => ({ id5: vars.id6 }))
      .withPreprocessor<{ id7: number }>((vars) => ({ id6: vars.id7 }))
      .withPreprocessor<{ id8: number }>((vars) => ({ id7: vars.id8 }))
      .withPreprocessor<{ id9: number }>((vars) => ({ id8: vars.id9 }))
      .withPreprocessor<{ id10: number }>((vars) => ({ id9: vars.id10 }))
      .withPreprocessor<{ id11: number }>((vars) => ({ id10: vars.id11 }))
      .withPreprocessor<{ id12: number }>((vars) => ({ id11: vars.id12 }))
      .withPreprocessor<{ id13: number }>((vars) => ({ id12: vars.id13 }))
      .withPreprocessor<{ id14: number }>((vars) => ({ id13: vars.id14 }))
      .withPreprocessor<{ id15: number }>((vars) => ({ id14: vars.id15 }))
      .withPreprocessor<{ id16: number }>((vars) => ({ id15: vars.id16 }))
      .withPreprocessor<{ id17: number }>((vars) => ({ id16: vars.id17 }))
      .withPreprocessor<{ id18: number }>((vars) => ({ id17: vars.id18 }))
      .withPreprocessor<{ id19: number }>((vars) => ({ id18: vars.id19 }))
      .withPreprocessor<{ id20: number }>((vars) => ({ id19: vars.id20 }))
      .withPreprocessor<{ id21: number }>((vars) => ({ id20: vars.id21 }))
      .withPreprocessor<{ id22: number }>((vars) => ({ id21: vars.id22 }))
      .withPreprocessor<{ id23: number }>((vars) => ({ id22: vars.id23 }))
      .withPreprocessor<{ id24: number }>((vars) => ({ id23: vars.id24 }))
      .withPreprocessor<{ id25: number }>((vars) => ({ id24: vars.id25 }))
      .withPreprocessor<{ id26: number }>((vars) => ({ id25: vars.id26 }))
      .withPreprocessor<{ id27: number }>((vars) => ({ id26: vars.id27 }))
      .withPreprocessor<{ id28: number }>((vars) => ({ id27: vars.id28 }))
      .withPreprocessor<{ id29: number }>((vars) => ({ id28: vars.id29 }))
      .withPreprocessor<{ id30: number }>((vars) => ({ id29: vars.id30 }))
      .withPreprocessor<{ id31: number }>((vars) => ({ id30: vars.id31 }))
      .withPreprocessor<{ id32: number }>((vars) => ({ id31: vars.id32 }))
      .withPreprocessor<{ id33: number }>((vars) => ({ id32: vars.id33 }))
      .withPreprocessor<{ id34: number }>((vars) => ({ id33: vars.id34 }))
      .withPreprocessor<{ id35: number }>((vars) => ({ id34: vars.id35 }))
      .withPreprocessor<{ id36: number }>((vars) => ({ id35: vars.id36 }))
      .withPreprocessor<{ id37: number }>((vars) => ({ id36: vars.id37 }))
      .withPreprocessor<{ id38: number }>((vars) => ({ id37: vars.id38 }))
      .withPreprocessor<{ id39: number }>((vars) => ({ id38: vars.id39 }))
      .withPreprocessor<{ id40: number }>((vars) => ({ id39: vars.id40 }))
      .withPreprocessor<{ id41: number }>((vars) => ({ id40: vars.id41 }))
      .withPreprocessor<{ id42: number }>((vars) => ({ id41: vars.id42 }))
      .withPreprocessor<{ id43: number }>((vars) => ({ id42: vars.id43 }))
      .withPreprocessor<{ id44: number }>((vars) => ({ id43: vars.id44 }))
      .withPreprocessor<{ id45: number }>((vars) => ({ id44: vars.id45 }))
      .withPreprocessor<{ id46: number }>((vars) => ({ id45: vars.id46 }))
      .withPreprocessor<{ id47: number }>((vars) => ({ id46: vars.id47 }))
      .withPreprocessor<{ id48: number }>((vars) => ({ id47: vars.id48 }))
      .withPreprocessor<{ id49: number }>((vars) => ({ id48: vars.id49 }))
      .withPreprocessor<{ id50: number }>((vars) => ({ id49: vars.id50 }))
      .withPreprocessor<{ id51: number }>((vars) => ({ id50: vars.id51 }))
      .withPreprocessor<{ id52: number }>((vars) => ({ id51: vars.id52 }))
      .withPreprocessor<{ id53: number }>((vars) => ({ id52: vars.id53 }))
      .withPreprocessor<{ id54: number }>((vars) => ({ id53: vars.id54 }))
      .withPreprocessor<{ id55: number }>((vars) => ({ id54: vars.id55 }))
      .withPreprocessor<{ id56: number }>((vars) => ({ id55: vars.id56 }))
      .withPreprocessor<{ id57: number }>((vars) => ({ id56: vars.id57 }))
      .withPreprocessor<{ id58: number }>((vars) => ({ id57: vars.id58 }))
      .withPreprocessor<{ id59: number }>((vars) => ({ id58: vars.id59 }))
      .withPreprocessor<{ id60: number }>((vars) => ({ id59: vars.id60 }))
      .withPreprocessor<{ id61: number }>((vars) => ({ id60: vars.id61 }))
      .withPreprocessor<{ id62: number }>((vars) => ({ id61: vars.id62 }))
      .withPreprocessor<{ id63: number }>((vars) => ({ id62: vars.id63 }))
      .withPreprocessor<{ id64: number }>((vars) => ({ id63: vars.id64 }))
      .withPreprocessor<{ id65: number }>((vars) => ({ id64: vars.id65 }))
      .withPreprocessor<{ id66: number }>((vars) => ({ id65: vars.id66 }))
      .withPreprocessor<{ id67: number }>((vars) => ({ id66: vars.id67 }))
      .withPreprocessor<{ id68: number }>((vars) => ({ id67: vars.id68 }))
      .withPreprocessor<{ id69: number }>((vars) => ({ id68: vars.id69 }))
      .withPreprocessor<{ id70: number }>((vars) => ({ id69: vars.id70 }))
      .withPreprocessor<{ id71: number }>((vars) => ({ id70: vars.id71 }))
      .withPreprocessor<{ id72: number }>((vars) => ({ id71: vars.id72 }))
      .withPreprocessor<{ id73: number }>((vars) => ({ id72: vars.id73 }))
      .withPreprocessor<{ id74: number }>((vars) => ({ id73: vars.id74 }))
      .withPreprocessor<{ id75: number }>((vars) => ({ id74: vars.id75 }))
      .withPreprocessor<{ id76: number }>((vars) => ({ id75: vars.id76 }))
      .withPreprocessor<{ id77: number }>((vars) => ({ id76: vars.id77 }))
      .withPreprocessor<{ id78: number }>((vars) => ({ id77: vars.id78 }))
      .withPreprocessor<{ id79: number }>((vars) => ({ id78: vars.id79 }))
      .withPreprocessor<{ id80: number }>((vars) => ({ id79: vars.id80 }))
      .withPreprocessor<{ id81: number }>((vars) => ({ id80: vars.id81 }))
      .withPreprocessor<{ id82: number }>((vars) => ({ id81: vars.id82 }))
      .withPreprocessor<{ id83: number }>((vars) => ({ id82: vars.id83 }))
      .withPreprocessor<{ id84: number }>((vars) => ({ id83: vars.id84 }))
      .withPreprocessor<{ id85: number }>((vars) => ({ id84: vars.id85 }))
      .withPreprocessor<{ id86: number }>((vars) => ({ id85: vars.id86 }))
      .withPreprocessor<{ id87: number }>((vars) => ({ id86: vars.id87 }))
      .withPreprocessor<{ id88: number }>((vars) => ({ id87: vars.id88 }))
      .withPreprocessor<{ id89: number }>((vars) => ({ id88: vars.id89 }))
      .withPreprocessor<{ id90: number }>((vars) => ({ id89: vars.id90 }))
      .withPreprocessor<{ id91: number }>((vars) => ({ id90: vars.id91 }))
      .withPreprocessor<{ id92: number }>((vars) => ({ id91: vars.id92 }))
      .withPreprocessor<{ id93: number }>((vars) => ({ id92: vars.id93 }))
      .withPreprocessor<{ id94: number }>((vars) => ({ id93: vars.id94 }))
      .withPreprocessor<{ id95: number }>((vars) => ({ id94: vars.id95 }))
      .withPreprocessor<{ id96: number }>((vars) => ({ id95: vars.id96 }))
      .withPreprocessor<{ id97: number }>((vars) => ({ id96: vars.id97 }))
      .withPreprocessor<{ id98: number }>((vars) => ({ id97: vars.id98 }))
      .withPreprocessor<{ id99: number }>((vars) => ({ id98: vars.id99 }))
      .withPreprocessor<{ id100: number }>((vars) => ({ id99: vars.id100 }))
      .withPreprocessor<{ id101: number }>((vars) => ({ id100: vars.id101 }))
      .withPreprocessor<{ id102: number }>((vars) => ({ id101: vars.id102 }))
      .withPreprocessor<{ id103: number }>((vars) => ({ id102: vars.id103 }))
      .withPreprocessor<{ id104: number }>((vars) => ({ id103: vars.id104 }))
      .withPreprocessor<{ id105: number }>((vars) => ({ id104: vars.id105 }))
      .withPreprocessor<{ id106: number }>((vars) => ({ id105: vars.id106 }))
      .withPreprocessor<{ id107: number }>((vars) => ({ id106: vars.id107 }));

    const { data, isSuccess } = nqb.useQuery({ id107: 5 });

    if (isSuccess) expectTypeOf(data).toEqualTypeOf<TData>();
  });

  it('should handle lots of withClient and withPagination', () => {
    const nqb = qb
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withPagination({ getNextPageParam: null! })
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!)
      .withClient(null!);

    const { data, isSuccess } = nqb.useQuery({ params: { id: 5 } });

    if (isSuccess) expectTypeOf(data).toEqualTypeOf<TData>();
  });
});
